import { test, expect, describe, beforeEach, afterEach } from "bun:test";
import { mkdtemp, rm, mkdir, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CLI = new URL("./cli.ts", import.meta.url).pathname;
const ROOT = new URL("..", import.meta.url).pathname;

async function runCli(args: string[], cwd: string) {
	const proc = Bun.spawn({
		cmd: ["bun", "run", CLI, ...args],
		cwd,
		stdout: "pipe",
		stderr: "pipe",
	});
	const [stdout, stderr, exitCode] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	]);
	return { stdout, stderr, exitCode };
}

async function runCommand(cmd: string[], cwd: string) {
	const proc = Bun.spawn({
		cmd,
		cwd,
		stdout: "pipe",
		stderr: "pipe",
	});
	const [stdout, stderr, exitCode] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	]);
	return { stdout, stderr, exitCode };
}

let dir: string;

beforeEach(async () => {
	dir = await mkdtemp(join(tmpdir(), "errkit-"));
});

afterEach(async () => {
	await rm(dir, { recursive: true, force: true });
});

describe("errkit init", () => {
	test("creates errkit.json with schema", async () => {
		const { exitCode, stdout } = await runCli(["init"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("Created");

		const contents = await readFile(join(dir, "errkit.json"), "utf8");
		expect(contents).toContain(`"$schema": "https://unpkg.com/errkit@latest/schema.json"`);
		expect(contents).toContain(`"outputs"`);
		expect(contents).toContain(`"common"`);
		expect(contents).toContain(`"scopes"`);
		expect(() => JSON.parse(contents)).not.toThrow();
		expect(contents).not.toMatch(/(^|\n)\s*\/\//);
	});

	test("refuses to overwrite existing config", async () => {
		await writeFile(join(dir, "errkit.json"), "{}");
		const { exitCode, stderr } = await runCli(["init"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("already exists");
	});
});

describe("errkit generate", () => {
	test("fails without errkit.json", async () => {
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toMatch(/not found|init/);
	});

	test("assigns missing codes and writes ts output", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.ts" }],
  "common": {
    "user_not_authorized": { "description": "User is not authorized" },
    "payment_failed": {}
  }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode, stdout } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("Assigned 2 codes");
		expect(stdout).toContain("errors.ts");

		const json = await readFile(join(dir, "errkit.json"), "utf8");
		expect(json).toMatch(/"user_not_authorized":\s*\{[^}]*"code":\s*"[A-Z2-9]{6}"/);
		expect(json).toMatch(/"payment_failed":\s*\{[^}]*"code":\s*"[A-Z2-9]{6}"/);

		const ts = await readFile(join(dir, "errors.ts"), "utf8");
		expect(ts).toContain("// AUTO-GENERATED BY ERRKIT");
		expect(ts).toContain("/* eslint-disable */");
		expect(ts).toContain("/* oxlint-disable */");
		expect(ts).not.toContain("prettier-ignore");
		expect(ts).not.toContain("oxfmt-ignore");
		expect(ts).toContain("/** User is not authorized */");
		expect(ts).toMatch(/UserNotAuthorized = "[A-Z2-9]{6}",/);
		expect(ts).toMatch(/PaymentFailed = "[A-Z2-9]{6}",/);
		expect(ts).not.toContain("user_not_authorized");
		expect(ts).not.toContain("payment_failed");
		// sorted by name
		expect(ts.indexOf("PaymentFailed")).toBeLessThan(ts.indexOf("UserNotAuthorized"));
	});

	test("normalizes entry names and overwrites config before generating", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.ts", "scopes": ["server"] }],
  "common": {
    "UserNotAuthorized": { "description": "User is not authorized" }
  },
  "scopes": {
    "server": {
      "DATABASE_UNAVAILABLE": { "code": "ABCDEF" }
    }
  }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode, stdout } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("Normalized 2 error names");

		const json = await readFile(join(dir, "errkit.json"), "utf8");
		expect(json).toContain(`"user_not_authorized"`);
		expect(json).toContain(`"database_unavailable"`);
		expect(json).not.toContain("UserNotAuthorized");
		expect(json).not.toContain("DATABASE_UNAVAILABLE");

		const ts = await readFile(join(dir, "errors.ts"), "utf8");
		expect(ts).toContain(`UserNotAuthorized = `);
		expect(ts).toContain(`DatabaseUnavailable = "ABCDEF",`);
	});

	test("go output honors explicit package field", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.go", "package": "mypkg" }],
  "common": { "foo": { "code": "ABCDEF" } }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		const go = await readFile(join(dir, "errors.go"), "utf8");
		expect(go).toContain("package mypkg");
	});

	test("writes go output with package from parent dir", async () => {
		const cfg = `{
  "outputs": [{ "path": "internal/errs/errors.go", "scopes": ["server"] }],
  "common": { "foo": { "code": "ABCDEF" } },
  "scopes": { "server": { "bar": { "code": "GHJKMN", "description": "bar" } } }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);

		const go = await readFile(join(dir, "internal/errs/errors.go"), "utf8");
		expect(go).toContain("// Code generated by errkit. DO NOT EDIT.");
		expect(go).toContain("package errs");
		expect(go).toContain("type Code string");
		expect(go).not.toContain("func (e Code) Error()");
		expect(go).toContain(`Foo Code = "ABCDEF"`);
		expect(go).toContain(`Bar Code = "GHJKMN"`);
		expect(go).not.toContain("ErrFoo");
		expect(go).toContain("// bar");
	});

	test("writes rust output", async () => {
		const cfg = `{
  "outputs": [{ "path": "src/errors.rs", "scopes": ["server"] }],
  "common": { "foo": { "code": "ABCDEF" } },
  "scopes": { "server": { "bar": { "code": "GHJKMN", "description": "bar" } } }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode, stdout } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("src/errors.rs");
		expect(stdout).toContain("(rs)");

		const rust = await readFile(join(dir, "src/errors.rs"), "utf8");
		expect(rust).toContain("// Code generated by errkit. DO NOT EDIT.");
		expect(rust).toContain("pub enum Err {");
		expect(rust).toContain("Foo,");
		expect(rust).toContain("Bar,");
		expect(rust).toContain("Self::Foo,");
		expect(rust).toContain("/// bar");
		expect(rust).toContain("pub fn from_code(code: &str) -> Option<Self>");
		expect(rust).toContain("impl fmt::Display for Err");
	});

	test("rejects comments in errkit.json", async () => {
		const cfg = `{
  // important note
  "common": {
    "foo": { "description": "x" } // trailing comment
  }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("not valid JSON");
	});

	test("refuses to overwrite an unmanaged output file", async () => {
		await writeFile(join(dir, "errkit.json"), `{ "outputs": [{ "path": "errors.ts" }], "common": { "foo": { "code": "ABCDEF" } } }`);
		await writeFile(join(dir, "errors.ts"), "export const hand_written = 1;\n");
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("not managed by errkit");

		const after = await readFile(join(dir, "errors.ts"), "utf8");
		expect(after).toContain("hand_written");
	});

	test("emits warning when a scope entry overrides a common entry", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.ts", "scopes": ["server"] }],
  "common": { "foo": { "code": "ABCDEF", "description": "from common" } },
  "scopes": { "server": { "foo": { "code": "GHJKMN", "description": "from server" } } }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stderr).toMatch(/warning.*overrides/);

		const ts = await readFile(join(dir, "errors.ts"), "utf8");
		expect(ts).toContain(`Foo = "GHJKMN"`);
		expect(ts).not.toContain("foo");
		expect(ts).toContain("from server");
	});

	test("reports generated name collisions without a stack trace", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.rs" }],
  "common": {
    "http404": { "code": "ABCDEF" },
    "http_404": { "code": "GHJKMN" }
  }
}
`;
		await writeFile(join(dir, "errkit.json"), cfg);
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("Error: errors.rs:");
		expect(stderr).toContain("both generate Rust variant Http404");
		expect(stderr).not.toContain("at ");
	});

	test("walks up to find errkit.json from a subdirectory", async () => {
		await writeFile(
			join(dir, "errkit.json"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "foo": { "code": "ABCDEF" } } }`,
		);
		const sub = join(dir, "nested", "deeper");
		await mkdir(sub, { recursive: true });
		const { exitCode } = await runCli(["generate"], sub);
		expect(exitCode).toBe(0);
		expect(existsSync(join(dir, "errors.ts"))).toBe(true);
	});

	test("does not rewrite output when content unchanged", async () => {
		await writeFile(
			join(dir, "errkit.json"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "foo": { "code": "ABCDEF" } } }`,
		);
		await runCli(["generate"], dir);
		const before = (await readFile(join(dir, "errors.ts"))).toString();
		const { stdout } = await runCli(["generate"], dir);
		const after = (await readFile(join(dir, "errors.ts"))).toString();
		expect(after).toBe(before);
		expect(stdout).toContain("Unchanged");
	});

	test("accepts `gen` and `g` as aliases for `generate`", async () => {
		await writeFile(
			join(dir, "errkit.json"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "foo": { "code": "ABCDEF" } } }`,
		);
		const gen = await runCli(["gen"], dir);
		expect(gen.exitCode).toBe(0);
		expect(existsSync(join(dir, "errors.ts"))).toBe(true);

		const g = await runCli(["g"], dir);
		expect(g.exitCode).toBe(0);
	});

	test("packed npm package runs with node", async () => {
		const build = await runCommand(["bun", "run", "build"], ROOT);
		expect(build.exitCode, build.stderr).toBe(0);

		const packDir = join(dir, "pack");
		const extractDir = join(dir, "extract");
		const projectDir = join(dir, "project");
		await mkdir(packDir, { recursive: true });
		await mkdir(extractDir, { recursive: true });
		await mkdir(projectDir, { recursive: true });

		const pack = await runCommand(["npm", "pack", "--pack-destination", packDir], ROOT);
		expect(pack.exitCode, pack.stderr).toBe(0);
		const tarball = pack.stdout.trim().split(/\r?\n/).at(-1);
		expect(tarball).toBeTruthy();

		const extract = await runCommand(["tar", "-xzf", join(packDir, tarball!), "-C", extractDir], ROOT);
		expect(extract.exitCode, extract.stderr).toBe(0);

		await writeFile(
			join(projectDir, "errkit.json"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "foo": { "code": "ABCDEF" } } }`,
		);
		const generate = await runCommand(["node", join(extractDir, "package", "dist", "cli.js"), "generate"], projectDir);
		expect(generate.exitCode, generate.stderr).toBe(0);

		const output = await readFile(join(projectDir, "errors.ts"), "utf8");
		expect(output).toContain(`Foo = "ABCDEF"`);
	});
});
