import { test, expect, describe, beforeEach, afterEach } from "bun:test";
import { mkdtemp, rm, mkdir, writeFile, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CLI = new URL("./cli.ts", import.meta.url).pathname;

async function runCli(args: string[], cwd: string) {
  const proc = Bun.spawn({
    cmd: ["bun", "run", CLI, ...args],
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { stdout, stderr, exitCode };
}

let dir: string;

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), "errkit-"));
});

afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

describe("errkit add", () => {
  test("creates errors.ts on first add", async () => {
    const { exitCode, stdout } = await runCli(
      ["add", "USER_NOT_AUTHORIZED", "--description", "User not authorized"],
      dir,
    );
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Added USER_NOT_AUTHORIZED");
    expect(stdout).toContain("errors.ts");

    const contents = await readFile(join(dir, "errors.ts"), "utf8");
    expect(contents).toContain("// AUTO-GENERATED BY ERRKIT");
    expect(contents).toContain("/** User not authorized */");
    expect(contents).toMatch(/USER_NOT_AUTHORIZED = "[A-Z2-9]{6}",/);
  });

  test("appends a second entry to an existing managed file", async () => {
    await runCli(["add", "USER_NOT_AUTHORIZED", "--description", "User not authorized"], dir);
    const { exitCode } = await runCli(
      ["add", "PAYMENT_FAILED", "--description", "Payment failed"],
      dir,
    );
    expect(exitCode).toBe(0);

    const contents = await readFile(join(dir, "errors.ts"), "utf8");
    expect(contents).toContain("USER_NOT_AUTHORIZED");
    expect(contents).toContain("PAYMENT_FAILED");
    // sorted by name: PAYMENT_FAILED comes before USER_NOT_AUTHORIZED
    expect(contents.indexOf("PAYMENT_FAILED")).toBeLessThan(
      contents.indexOf("USER_NOT_AUTHORIZED"),
    );
  });

  test("omits JSDoc when no description is given", async () => {
    const { exitCode } = await runCli(["add", "BARE"], dir);
    expect(exitCode).toBe(0);
    const contents = await readFile(join(dir, "errors.ts"), "utf8");
    expect(contents).not.toContain("/**");
    expect(contents).toMatch(/BARE = "[A-Z2-9]{6}",/);
  });

  test("rejects duplicate names", async () => {
    await runCli(["add", "FOO"], dir);
    const { exitCode, stderr } = await runCli(["add", "FOO"], dir);
    expect(exitCode).not.toBe(0);
    expect(stderr.toLowerCase()).toContain("already exists");
  });

  test("rejects invalid names", async () => {
    const { exitCode, stderr } = await runCli(["add", "lowercase_name"], dir);
    expect(exitCode).not.toBe(0);
    expect(stderr).toMatch(/NAME|name/);
  });

  test("refuses to overwrite an unmanaged errors.ts in cwd", async () => {
    const unmanaged = `export const something = 1;\n`;
    await writeFile(join(dir, "errors.ts"), unmanaged);
    const { exitCode, stderr } = await runCli(["add", "FOO"], dir);
    expect(exitCode).not.toBe(0);
    expect(stderr).toContain("not managed by errkit");

    const after = await readFile(join(dir, "errors.ts"), "utf8");
    expect(after).toBe(unmanaged);
  });

  test("walks upward past unmanaged errors.ts to find a managed parent", async () => {
    const sub = join(dir, "pkg", "nested");
    await mkdir(sub, { recursive: true });
    // unmanaged at nested level — should be skipped
    await writeFile(join(dir, "pkg", "errors.ts"), "export const x = 1;\n");
    // seed a managed file higher up via the CLI itself
    await runCli(["add", "SEED"], dir);

    const { exitCode } = await runCli(["add", "CHILD"], sub);
    expect(exitCode).toBe(0);

    const rootContents = await readFile(join(dir, "errors.ts"), "utf8");
    expect(rootContents).toContain("SEED");
    expect(rootContents).toContain("CHILD");
  });

  test("--output targets an explicit path, creating it if missing", async () => {
    const target = join(dir, "nested", "catalog.ts");
    await mkdir(join(dir, "nested"));
    const { exitCode } = await runCli(["add", "FOO", "-o", target], dir);
    expect(exitCode).toBe(0);
    const contents = await readFile(target, "utf8");
    expect(contents).toContain("FOO");
    expect(contents).toContain("// AUTO-GENERATED BY ERRKIT");
  });

  test("--output refuses to overwrite an unmanaged file", async () => {
    const target = join(dir, "catalog.ts");
    await writeFile(target, "export const foo = 1;\n");
    const { exitCode, stderr } = await runCli(["add", "FOO", "--output", target], dir);
    expect(exitCode).not.toBe(0);
    expect(stderr).toContain("not managed by errkit");
  });
});
