import { test, expect, describe, beforeEach, afterEach } from "bun:test";
import { mkdtemp, rm, mkdir, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CLI = new URL("./cli.ts", import.meta.url).pathname;

async function runCli(args: string[], cwd: string) {
	const proc = Bun.spawn({
		cmd: ["bun", "run", CLI, ...args],
		cwd,
		stdout: "pipe",
		stderr: "pipe",
	});
	const [stdout, stderr, exitCode] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	]);
	return { stdout, stderr, exitCode };
}

let dir: string;

beforeEach(async () => {
	dir = await mkdtemp(join(tmpdir(), "errkit-"));
});

afterEach(async () => {
	await rm(dir, { recursive: true, force: true });
});

describe("errkit init", () => {
	test("creates errkit.jsonc with schema and comments", async () => {
		const { exitCode, stdout } = await runCli(["init"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("Created");

		const contents = await readFile(join(dir, "errkit.jsonc"), "utf8");
		expect(contents).toContain(`"$schema": "https://unpkg.com/errkit@latest/schema.json"`);
		expect(contents).toContain(`"outputs"`);
		expect(contents).toContain(`"common"`);
		expect(contents).toContain(`"scopes"`);
		// comments preserved in the starter
		expect(contents).toMatch(/\/\/ errkit configuration/);
	});

	test("refuses to overwrite existing config", async () => {
		await writeFile(join(dir, "errkit.jsonc"), "{}");
		const { exitCode, stderr } = await runCli(["init"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("already exists");
	});
});

describe("errkit generate", () => {
	test("fails without errkit.jsonc", async () => {
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toMatch(/not found|init/);
	});

	test("assigns missing codes and writes ts output", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.ts" }],
  "common": {
    "USER_NOT_AUTHORIZED": { "description": "User is not authorized" },
    "PAYMENT_FAILED": {}
  }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode, stdout } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("Assigned 2 codes");
		expect(stdout).toContain("errors.ts");

		const jsonc = await readFile(join(dir, "errkit.jsonc"), "utf8");
		expect(jsonc).toMatch(/"USER_NOT_AUTHORIZED":\s*\{[^}]*"code":\s*"[A-Z2-9]{6}"/);
		expect(jsonc).toMatch(/"PAYMENT_FAILED":\s*\{[^}]*"code":\s*"[A-Z2-9]{6}"/);

		const ts = await readFile(join(dir, "errors.ts"), "utf8");
		expect(ts).toContain("// AUTO-GENERATED BY ERRKIT");
		expect(ts).toContain("/** User is not authorized */");
		expect(ts).toMatch(/UserNotAuthorized = "[A-Z2-9]{6}",/);
		expect(ts).toMatch(/PaymentFailed = "[A-Z2-9]{6}",/);
		expect(ts).not.toContain("USER_NOT_AUTHORIZED");
		expect(ts).not.toContain("PAYMENT_FAILED");
		// sorted by name
		expect(ts.indexOf("PaymentFailed")).toBeLessThan(ts.indexOf("UserNotAuthorized"));
	});

	test("go output honors explicit package field", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.go", "package": "mypkg" }],
  "common": { "FOO": { "code": "ABCDEF" } }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		const go = await readFile(join(dir, "errors.go"), "utf8");
		expect(go).toContain("package mypkg");
	});

	test("writes go output with package from parent dir", async () => {
		const cfg = `{
  "outputs": [{ "path": "internal/errs/errors.go", "scopes": ["server"] }],
  "common": { "FOO": { "code": "ABCDEF" } },
  "scopes": { "server": { "BAR": { "code": "GHJKMN", "description": "bar" } } }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);

		const go = await readFile(join(dir, "internal/errs/errors.go"), "utf8");
		expect(go).toContain("// Code generated by errkit. DO NOT EDIT.");
		expect(go).toContain("package errs");
		expect(go).toContain("type Err string");
		expect(go).toContain(`Foo Err = "ABCDEF"`);
		expect(go).toContain(`Bar Err = "GHJKMN"`);
		expect(go).toContain("// bar");
	});

	test("writes rust output", async () => {
		const cfg = `{
  "outputs": [{ "path": "src/errors.rs", "scopes": ["server"] }],
  "common": { "FOO": { "code": "ABCDEF" } },
  "scopes": { "server": { "BAR": { "code": "GHJKMN", "description": "bar" } } }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode, stdout } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stdout).toContain("src/errors.rs");
		expect(stdout).toContain("(rs)");

		const rust = await readFile(join(dir, "src/errors.rs"), "utf8");
		expect(rust).toContain("// Code generated by errkit. DO NOT EDIT.");
		expect(rust).toContain("pub enum Err {");
		expect(rust).toContain("Foo,");
		expect(rust).toContain("Bar,");
		expect(rust).not.toContain("FOO");
		expect(rust).not.toContain("BAR");
		expect(rust).toContain("Self::Foo,");
		expect(rust).toContain("/// bar");
		expect(rust).toContain("pub fn from_code(code: &str) -> Option<Self>");
		expect(rust).toContain("impl fmt::Display for Err");
	});

	test("preserves comments in errkit.jsonc when backfilling codes", async () => {
		const cfg = `{
  // important note
  "common": {
    "FOO": { "description": "x" } // trailing comment
  }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);

		const after = await readFile(join(dir, "errkit.jsonc"), "utf8");
		expect(after).toContain("// important note");
		expect(after).toContain("// trailing comment");
	});

	test("refuses to overwrite an unmanaged output file", async () => {
		await writeFile(join(dir, "errkit.jsonc"), `{ "outputs": [{ "path": "errors.ts" }], "common": { "FOO": { "code": "ABCDEF" } } }`);
		await writeFile(join(dir, "errors.ts"), "export const hand_written = 1;\n");
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("not managed by errkit");

		const after = await readFile(join(dir, "errors.ts"), "utf8");
		expect(after).toContain("hand_written");
	});

	test("emits warning when a scope entry overrides a common entry", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.ts", "scopes": ["server"] }],
  "common": { "FOO": { "code": "ABCDEF", "description": "from common" } },
  "scopes": { "server": { "FOO": { "code": "GHJKMN", "description": "from server" } } }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).toBe(0);
		expect(stderr).toMatch(/warning.*overrides/);

		const ts = await readFile(join(dir, "errors.ts"), "utf8");
		expect(ts).toContain(`Foo = "GHJKMN"`);
		expect(ts).not.toContain("FOO");
		expect(ts).toContain("from server");
	});

	test("reports generated name collisions without a stack trace", async () => {
		const cfg = `{
  "outputs": [{ "path": "errors.rs" }],
  "common": {
    "FOO_BAR": { "code": "ABCDEF" },
    "FOO__BAR": { "code": "GHJKMN" }
  }
}
`;
		await writeFile(join(dir, "errkit.jsonc"), cfg);
		const { exitCode, stderr } = await runCli(["generate"], dir);
		expect(exitCode).not.toBe(0);
		expect(stderr).toContain("Error: errors.rs:");
		expect(stderr).toContain("both generate Rust variant FooBar");
		expect(stderr).not.toContain("at ");
	});

	test("walks up to find errkit.jsonc from a subdirectory", async () => {
		await writeFile(
			join(dir, "errkit.jsonc"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "FOO": { "code": "ABCDEF" } } }`,
		);
		const sub = join(dir, "nested", "deeper");
		await mkdir(sub, { recursive: true });
		const { exitCode } = await runCli(["generate"], sub);
		expect(exitCode).toBe(0);
		expect(existsSync(join(dir, "errors.ts"))).toBe(true);
	});

	test("does not rewrite output when content unchanged", async () => {
		await writeFile(
			join(dir, "errkit.jsonc"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "FOO": { "code": "ABCDEF" } } }`,
		);
		await runCli(["generate"], dir);
		const before = (await readFile(join(dir, "errors.ts"))).toString();
		const { stdout } = await runCli(["generate"], dir);
		const after = (await readFile(join(dir, "errors.ts"))).toString();
		expect(after).toBe(before);
		expect(stdout).toContain("Unchanged");
	});

	test("accepts `gen` and `g` as aliases for `generate`", async () => {
		await writeFile(
			join(dir, "errkit.jsonc"),
			`{ "outputs": [{ "path": "errors.ts" }], "common": { "FOO": { "code": "ABCDEF" } } }`,
		);
		const gen = await runCli(["gen"], dir);
		expect(gen.exitCode).toBe(0);
		expect(existsSync(join(dir, "errors.ts"))).toBe(true);

		const g = await runCli(["g"], dir);
		expect(g.exitCode).toBe(0);
	});
});
