import { test, expect, describe } from "bun:test";
import {
  isValidName,
  hasMarker,
  generateCode,
  renderFile,
  parseManagedFile,
  MARKER,
  ALPHABET,
  CODE_LENGTH,
  type Entry,
} from "./lib.ts";

describe("isValidName", () => {
  test("accepts uppercase snake case", () => {
    expect(isValidName("USER_NOT_AUTHORIZED")).toBe(true);
    expect(isValidName("PAYMENT_FAILED")).toBe(true);
    expect(isValidName("HTTP_404")).toBe(true);
    expect(isValidName("A")).toBe(true);
  });

  test("rejects lowercase", () => {
    expect(isValidName("user_not_authorized")).toBe(false);
  });

  test("rejects camel/pascal case", () => {
    expect(isValidName("UserNotAuthorized")).toBe(false);
  });

  test("rejects leading digit", () => {
    expect(isValidName("404_ERROR")).toBe(false);
  });

  test("rejects hyphen", () => {
    expect(isValidName("USER-ERROR")).toBe(false);
  });

  test("rejects empty", () => {
    expect(isValidName("")).toBe(false);
  });
});

describe("hasMarker", () => {
  test("detects marker in first lines", () => {
    const content = `${MARKER}\n// This file is managed by errkit.\n\nexport enum Err {}\n`;
    expect(hasMarker(content)).toBe(true);
  });

  test("returns false for unmarked file", () => {
    const content = `export enum Err {\n  FOO = "bar",\n}\n`;
    expect(hasMarker(content)).toBe(false);
  });

  test("only scans near top", () => {
    const filler = "// x\n".repeat(200);
    const content = `${filler}${MARKER}\n`;
    expect(hasMarker(content)).toBe(false);
  });
});

describe("generateCode", () => {
  test("produces code of configured length from safe alphabet", () => {
    const code = generateCode(new Set());
    expect(code).toHaveLength(CODE_LENGTH);
    for (const ch of code) {
      expect(ALPHABET).toContain(ch);
    }
  });

  test("excludes ambiguous characters", () => {
    expect(ALPHABET).not.toContain("I");
    expect(ALPHABET).not.toContain("L");
    expect(ALPHABET).not.toContain("O");
    expect(ALPHABET).not.toContain("0");
    expect(ALPHABET).not.toContain("1");
  });

  test("avoids collisions with existing codes", () => {
    const existing = new Set<string>();
    for (let i = 0; i < 200; i++) {
      const code = generateCode(existing);
      expect(existing.has(code)).toBe(false);
      existing.add(code);
    }
  });
});

describe("renderFile", () => {
  test("writes header, sorted entries, JSDoc for descriptions", () => {
    const entries: Entry[] = [
      { name: "USER_NOT_AUTHORIZED", code: "K7M2QP", description: "User not authorized" },
      { name: "PAYMENT_FAILED", code: "A9X4TR", description: "Payment failed" },
    ];
    const out = renderFile(entries);
    expect(out).toBe(
      `// AUTO-GENERATED BY ERRKIT. DO NOT EDIT MANUALLY.
// This file is managed by errkit.

export enum Err {
  /** Payment failed */
  PAYMENT_FAILED = "A9X4TR",

  /** User not authorized */
  USER_NOT_AUTHORIZED = "K7M2QP",
}
`,
    );
  });

  test("omits JSDoc when no description", () => {
    const entries: Entry[] = [{ name: "FOO", code: "ABCDEF" }];
    const out = renderFile(entries);
    expect(out).toContain(`  FOO = "ABCDEF",\n`);
    expect(out).not.toContain("/**");
  });

  test("empty entries still renders valid enum", () => {
    const out = renderFile([]);
    expect(out).toContain("export enum Err {");
    expect(out).toContain("}");
  });
});

describe("parseManagedFile", () => {
  test("round trips with renderFile", () => {
    const entries: Entry[] = [
      { name: "AAA", code: "QQQQQQ", description: "first one" },
      { name: "BBB", code: "WWWWWW" },
      { name: "CCC", code: "EEEEEE", description: "third, with, commas" },
    ];
    const rendered = renderFile(entries);
    const parsed = parseManagedFile(rendered);
    // sorted by name
    expect(parsed).toEqual([
      { name: "AAA", code: "QQQQQQ", description: "first one" },
      { name: "BBB", code: "WWWWWW" },
      { name: "CCC", code: "EEEEEE", description: "third, with, commas" },
    ]);
  });

  test("throws on unmarked content", () => {
    expect(() => parseManagedFile(`export enum Err {}\n`)).toThrow();
  });

  test("throws on malformed enum body", () => {
    const bad = `${MARKER}\n// This file is managed by errkit.\n\nexport enum Err {\n  garbage\n}\n`;
    expect(() => parseManagedFile(bad)).toThrow();
  });

  test("parses empty enum", () => {
    const content = `${MARKER}\n// This file is managed by errkit.\n\nexport enum Err {\n}\n`;
    expect(parseManagedFile(content)).toEqual([]);
  });
});
