import {
	parse as parseJsonc,
	visit,
	modify,
	applyEdits,
	type JSONPath,
	type ParseError,
} from "jsonc-parser/lib/esm/main.js";

export type Entry = {
	name: string;
	code: string;
	description?: string;
};

export type Lang = "ts" | "go" | "rs";

export type Output = {
	path: string;
	scopes?: string[];
	package?: string;
};

export function langFromPath(path: string): Lang {
	if (path.endsWith(".ts")) return "ts";
	if (path.endsWith(".go")) return "go";
	if (path.endsWith(".rs")) return "rs";
	throw new Error(`cannot infer language from path "${path}" — expected .ts, .go, or .rs`);
}

export type RawEntry = {
	code?: string;
	description?: string;
};

export type Config = {
	$schema?: string;
	outputs?: Output[];
	common?: Record<string, RawEntry>;
	scopes?: Record<string, Record<string, RawEntry>>;
};

export const ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
export const CODE_LENGTH = 6;

const NAME_RE = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/;
const CODE_RE = /^[ABCDEFGHJKMNPQRSTUVWXYZ2-9]{6}$/;

export const TS_MARKER = "// AUTO-GENERATED BY ERRKIT. DO NOT EDIT MANUALLY.";
export const GO_MARKER = "// Code generated by errkit. DO NOT EDIT.";
export const RUST_MARKER = "// Code generated by errkit. DO NOT EDIT.";

const MARKER_SCAN_LINES = 10;

export function isValidName(name: string): boolean {
	return NAME_RE.test(name);
}

export function normalizeName(name: string): string {
	return name
		.trim()
		.replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
		.replace(/([a-z0-9])([A-Z])/g, "$1_$2")
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "_")
		.replace(/^_+|_+$/g, "")
		.replace(/_+/g, "_");
}

export function isValidCode(code: string): boolean {
	return CODE_RE.test(code);
}

export function normalizeEntryNames(content: string): { content: string; changed: number } {
	const errors: ParseError[] = [];
	parseJsonc(content, errors, { allowTrailingComma: true });
	if (errors.length > 0) return { content, changed: 0 };

	const byContainer = new Map<string, Map<string, string[]>>();
	const edits: { offset: number; length: number; replacement: string }[] = [];

	visit(
		content,
		{
			onObjectProperty(property, offset, length, _startLine, _startCharacter, pathSupplier) {
				const path = pathSupplier();
				if (!isEntryContainerPath(path)) return;

				const normalized = normalizeName(property);
				if (!isValidName(normalized)) return;

				const containerKey = JSON.stringify(path);
				let names = byContainer.get(containerKey);
				if (!names) {
					names = new Map();
					byContainer.set(containerKey, names);
				}
				const originals = names.get(normalized) ?? [];
				originals.push(property);
				names.set(normalized, originals);

				if (normalized !== property) {
					edits.push({ offset, length, replacement: JSON.stringify(normalized) });
				}
			},
		},
		{ allowTrailingComma: true },
	);

	for (const names of byContainer.values()) {
		for (const [normalized, originals] of names) {
			if (originals.length > 1) {
				throw new Error(
					`entries ${originals.map((name) => JSON.stringify(name)).join(" and ")} would both normalize to "${normalized}"`,
				);
			}
		}
	}

	let current = content;
	for (const edit of edits.sort((a, b) => b.offset - a.offset)) {
		current = current.slice(0, edit.offset) + edit.replacement + current.slice(edit.offset + edit.length);
	}
	return { content: current, changed: edits.length };
}

function isEntryContainerPath(path: JSONPath): boolean {
	return (
		(path.length === 1 && path[0] === "common") ||
		(path.length === 2 && path[0] === "scopes" && typeof path[1] === "string")
	);
}

export function generateCode(existing: Set<string>): string {
	while (true) {
		const bytes = crypto.getRandomValues(new Uint8Array(CODE_LENGTH));
		let code = "";
		for (let i = 0; i < CODE_LENGTH; i++) {
			code += ALPHABET[bytes[i]! % ALPHABET.length];
		}
		if (!existing.has(code)) return code;
	}
}

export function parseConfig(content: string): Config {
	const errors: ParseError[] = [];
	const data = parseJsonc(content, errors, { allowTrailingComma: true });
	if (errors.length > 0) {
		throw new Error(`errkit.jsonc is not valid JSONC: ${errors[0]!.error}`);
	}
	if (data === undefined || data === null || typeof data !== "object" || Array.isArray(data)) {
		throw new Error("errkit.jsonc must be a JSON object");
	}
	return validateConfig(data);
}

function validateConfig(data: unknown): Config {
	const cfg = data as Record<string, unknown>;
	const out: Config = {};

	if ("$schema" in cfg) {
		if (typeof cfg.$schema !== "string") throw new Error("$schema must be a string");
		out.$schema = cfg.$schema;
	}

	if ("outputs" in cfg && cfg.outputs !== undefined) {
		if (!Array.isArray(cfg.outputs)) throw new Error("outputs must be an array");
		out.outputs = cfg.outputs.map((o, i) => validateOutput(o, i));
	}

	if ("common" in cfg && cfg.common !== undefined) {
		out.common = validateEntryMap(cfg.common, "common");
	}

	if ("scopes" in cfg && cfg.scopes !== undefined) {
		if (typeof cfg.scopes !== "object" || cfg.scopes === null || Array.isArray(cfg.scopes)) {
			throw new Error("scopes must be an object");
		}
		const scopes: Record<string, Record<string, RawEntry>> = {};
		for (const [name, value] of Object.entries(cfg.scopes)) {
			scopes[name] = validateEntryMap(value, `scopes.${name}`);
		}
		out.scopes = scopes;
	}

	return out;
}

function validateOutput(raw: unknown, index: number): Output {
	if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
		throw new Error(`outputs[${index}] must be an object`);
	}
	const o = raw as Record<string, unknown>;
	if (typeof o.path !== "string" || o.path === "") {
		throw new Error(`outputs[${index}].path must be a non-empty string`);
	}
	if (!o.path.endsWith(".ts") && !o.path.endsWith(".go") && !o.path.endsWith(".rs")) {
		throw new Error(`outputs[${index}].path must end in .ts, .go, or .rs`);
	}
	const out: Output = { path: o.path };
	if ("scopes" in o && o.scopes !== undefined) {
		if (!Array.isArray(o.scopes) || !o.scopes.every((s) => typeof s === "string")) {
			throw new Error(`outputs[${index}].scopes must be an array of strings`);
		}
		out.scopes = o.scopes;
	}
	if ("package" in o && o.package !== undefined) {
		if (typeof o.package !== "string") {
			throw new Error(`outputs[${index}].package must be a string`);
		}
		out.package = o.package;
	}
	return out;
}

function validateEntryMap(raw: unknown, label: string): Record<string, RawEntry> {
	if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
		throw new Error(`${label} must be an object`);
	}
	const entries: Record<string, RawEntry> = {};
	for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
		if (!isValidName(name)) {
			throw new Error(`${label}.${name}: name must match ^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$`);
		}
		if (typeof value !== "object" || value === null || Array.isArray(value)) {
			throw new Error(`${label}.${name} must be an object`);
		}
		const v = value as Record<string, unknown>;
		const entry: RawEntry = {};
		if ("code" in v && v.code !== undefined) {
			if (typeof v.code !== "string" || !isValidCode(v.code)) {
				throw new Error(`${label}.${name}.code must match ^[A-Z2-9]{6}$`);
			}
			entry.code = v.code;
		}
		if ("description" in v && v.description !== undefined) {
			if (typeof v.description !== "string") {
				throw new Error(`${label}.${name}.description must be a string`);
			}
			entry.description = v.description;
		}
		entries[name] = entry;
	}
	return entries;
}

export function collectAllCodes(config: Config): Set<string> {
	const codes = new Set<string>();
	for (const e of Object.values(config.common ?? {})) {
		if (e.code) codes.add(e.code);
	}
	for (const scope of Object.values(config.scopes ?? {})) {
		for (const e of Object.values(scope)) {
			if (e.code) codes.add(e.code);
		}
	}
	return codes;
}

export type CollectResult = {
	entries: Entry[];
	warnings: string[];
};

export function collectEntries(config: Config, output: Output): CollectResult {
	const byName = new Map<string, { entry: Entry; source: string }>();
	const warnings: string[] = [];

	const toEntry = (name: string, raw: RawEntry): Entry => {
		if (!raw.code) {
			throw new Error(`entry "${name}" is missing a code — run \`errkit generate\` to assign one`);
		}
		const entry: Entry = { name, code: raw.code };
		if (raw.description !== undefined) entry.description = raw.description;
		return entry;
	};

	for (const [name, raw] of Object.entries(config.common ?? {})) {
		byName.set(name, { entry: toEntry(name, raw), source: "common" });
	}

	for (const scopeName of output.scopes ?? []) {
		const scope = config.scopes?.[scopeName];
		if (!scope) {
			throw new Error(`output references unknown scope "${scopeName}"`);
		}
		for (const [name, raw] of Object.entries(scope)) {
			const existing = byName.get(name);
			if (existing) {
				warnings.push(
					`"${name}" in scope "${scopeName}" overrides entry from ${existing.source} for output ${output.path}`,
				);
			}
			byName.set(name, { entry: toEntry(name, raw), source: `scopes.${scopeName}` });
		}
	}

	const entries = [...byName.values()]
		.map((v) => v.entry)
		.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
	return { entries, warnings };
}

export type Missing = { path: (string | number)[] };

export function findMissingCodes(config: Config): Missing[] {
	const missing: Missing[] = [];
	for (const [name, entry] of Object.entries(config.common ?? {})) {
		if (!entry.code) missing.push({ path: ["common", name, "code"] });
	}
	for (const [scopeName, scope] of Object.entries(config.scopes ?? {})) {
		for (const [name, entry] of Object.entries(scope)) {
			if (!entry.code) missing.push({ path: ["scopes", scopeName, name, "code"] });
		}
	}
	return missing;
}

export function backfillCodes(
	content: string,
	config: Config,
): { content: string; added: number } {
	const missing = findMissingCodes(config);
	if (missing.length === 0) return { content, added: 0 };

	const used = collectAllCodes(config);
	let current = content;
	for (const m of missing) {
		const code = generateCode(used);
		used.add(code);
		const edits = modify(current, m.path, code, {
			formattingOptions: { tabSize: 2, insertSpaces: true },
		});
		current = applyEdits(current, edits);
	}
	return { content: current, added: missing.length };
}

export function renderTs(entries: Entry[]): string {
	const tsEntries = entries.map((entry) => ({ ...entry, member: pascalCaseName(entry.name) }));
	assertUniqueGeneratedNames(
		tsEntries.map((entry) => ({ source: entry.name, generated: entry.member })),
		"TypeScript enum member",
	);
	const lines: string[] = [
		TS_MARKER,
		"/* eslint-disable */",
		"/* oxlint-disable */",
		"// This file is managed by errkit.",
		"",
		"export enum Err {",
	];
	tsEntries.forEach((entry, i) => {
		if (i > 0) lines.push("");
		if (entry.description) lines.push(`  /** ${entry.description} */`);
		lines.push(`  ${entry.member} = ${JSON.stringify(entry.code)},`);
	});
	lines.push("}", "");
	return lines.join("\n");
}

export function renderGo(entries: Entry[], packageName: string): string {
	const goEntries = entries.map((entry) => ({ ...entry, goName: pascalCaseName(entry.name) }));
	assertUniqueGeneratedNames(
		goEntries.map((entry) => ({ source: entry.name, generated: entry.goName })),
		"Go constant",
	);
	const lines: string[] = [
		GO_MARKER,
		"",
		`package ${packageName}`,
		"",
		"type Err string",
		"",
	];
	if (entries.length === 0) {
		lines.push("const ()", "");
		return lines.join("\n");
	}
	lines.push("const (");
	goEntries.forEach((entry, i) => {
		if (i > 0) lines.push("");
		if (entry.description) lines.push(`\t// ${entry.description}`);
		lines.push(`\t${entry.goName} Err = ${JSON.stringify(entry.code)}`);
	});
	lines.push(")", "");
	return lines.join("\n");
}

function rustDocLines(description: string): string[] {
	return description.split(/\r?\n/).map((line) => `    /// ${line}`);
}

function pascalCaseName(name: string): string {
	return name
		.split("_")
		.filter((part) => part.length > 0)
		.map((part) => part[0]!.toUpperCase() + part.slice(1).toLowerCase())
		.join("");
}

function assertUniqueGeneratedNames(
	names: { source: string; generated: string }[],
	label: string,
): void {
	const seen = new Map<string, string>();
	for (const name of names) {
		const existing = seen.get(name.generated);
		if (existing) {
			throw new Error(
				`entries "${existing}" and "${name.source}" both generate ${label} ${name.generated}`,
			);
		}
		seen.set(name.generated, name.source);
	}
}

function assertValidRustVariants(entries: { name: string; variant: string }[]): void {
	for (const entry of entries) {
		if (entry.variant === "Self") {
			throw new Error(`entry "${entry.name}" generates reserved Rust variant name Self`);
		}
	}
}

export function renderRust(entries: Entry[]): string {
	const rustEntries = entries.map((entry) => ({ ...entry, variant: pascalCaseName(entry.name) }));
	assertUniqueGeneratedNames(
		rustEntries.map((entry) => ({ source: entry.name, generated: entry.variant })),
		"Rust variant",
	);
	assertValidRustVariants(rustEntries);

	const lines: string[] = [
		RUST_MARKER,
		"",
		"use std::fmt;",
		"",
		"#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]",
		"pub enum Err {",
	];
	for (const entry of rustEntries) {
		if (entry.description) lines.push(...rustDocLines(entry.description));
		lines.push(`    ${entry.variant},`);
	}
	lines.push(
		"}",
		"",
		"impl Err {",
	);
	if (rustEntries.length > 0) {
		lines.push("    pub const ALL: &'static [Self] = &[");
		for (const entry of rustEntries) {
			lines.push(`        Self::${entry.variant},`);
		}
		lines.push("    ];");
	} else {
		lines.push("", "    pub const ALL: &'static [Self] = &[];");
	}
	lines.push(
		"",
		"    pub const fn as_str(self) -> &'static str {",
		"        match self {",
	);
	for (const entry of rustEntries) {
		lines.push(`            Self::${entry.variant} => ${JSON.stringify(entry.code)},`);
	}
	lines.push(
		"        }",
		"    }",
		"",
		"    pub fn from_code(code: &str) -> Option<Self> {",
		"        match code {",
	);
	for (const entry of rustEntries) {
		lines.push(`            ${JSON.stringify(entry.code)} => Some(Self::${entry.variant}),`);
	}
	lines.push(
		"            _ => None,",
		"        }",
		"    }",
		"}",
		"",
		"impl AsRef<str> for Err {",
		"    fn as_ref(&self) -> &str {",
		"        self.as_str()",
		"    }",
		"}",
		"",
		"impl fmt::Display for Err {",
		"    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {",
		"        f.write_str(self.as_str())",
		"    }",
	"}",
		"",
		"impl std::error::Error for Err {}",
		"",
	);
	return lines.join("\n");
}

export function hasMarker(content: string, marker: string): boolean {
	const head = content.split("\n", MARKER_SCAN_LINES);
	return head.some((line) => line.trim() === marker);
}

export function markerFor(lang: Lang): string {
	if (lang === "ts") return TS_MARKER;
	if (lang === "go") return GO_MARKER;
	return RUST_MARKER;
}
