export type Entry = {
  name: string;
  code: string;
  description?: string;
};

export const MARKER = "// AUTO-GENERATED BY ERRKIT. DO NOT EDIT MANUALLY.";
const SUBMARKER = "// This file is managed by errkit.";
const MARKER_SCAN_LINES = 10;

export const ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
export const CODE_LENGTH = 6;

const NAME_RE = /^[A-Z][A-Z0-9_]*$/;

export function isValidName(name: string): boolean {
  return NAME_RE.test(name);
}

export function hasMarker(content: string): boolean {
  const head = content.split("\n", MARKER_SCAN_LINES);
  return head.some((line) => line.trim() === MARKER);
}

export function generateCode(existing: Set<string>): string {
  while (true) {
    const bytes = crypto.getRandomValues(new Uint8Array(CODE_LENGTH));
    let code = "";
    for (let i = 0; i < CODE_LENGTH; i++) {
      code += ALPHABET[bytes[i]! % ALPHABET.length];
    }
    if (!existing.has(code)) return code;
  }
}

export function renderFile(entries: Entry[]): string {
  const sorted = [...entries].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const lines: string[] = [MARKER, SUBMARKER, "", "export enum Err {"];
  sorted.forEach((entry, i) => {
    if (i > 0) lines.push("");
    if (entry.description) lines.push(`  /** ${entry.description} */`);
    lines.push(`  ${entry.name} = ${JSON.stringify(entry.code)},`);
  });
  lines.push("}", "");
  return lines.join("\n");
}

const ENTRY_RE = /^\s*([A-Z][A-Z0-9_]*)\s*=\s*"([^"]+)"\s*,\s*$/;
const JSDOC_RE = /^\s*\/\*\*\s*(.*?)\s*\*\/\s*$/;
const ENUM_OPEN_RE = /^\s*export\s+enum\s+Err\s*\{\s*$/;
const ENUM_CLOSE_RE = /^\s*\}\s*$/;

export function parseManagedFile(content: string): Entry[] {
  if (!hasMarker(content)) {
    throw new Error("missing errkit marker");
  }
  const lines = content.split("\n");
  let i = 0;
  while (i < lines.length && !ENUM_OPEN_RE.test(lines[i]!)) i++;
  if (i === lines.length) throw new Error("no enum declaration found");
  i++;

  const entries: Entry[] = [];
  let pendingDescription: string | undefined;

  for (; i < lines.length; i++) {
    const line = lines[i]!;
    if (ENUM_CLOSE_RE.test(line)) {
      if (pendingDescription !== undefined) {
        throw new Error(`dangling JSDoc comment before closing brace`);
      }
      return entries;
    }
    if (line.trim() === "") {
      continue;
    }
    const jsdoc = JSDOC_RE.exec(line);
    if (jsdoc) {
      if (pendingDescription !== undefined) {
        throw new Error(`unexpected duplicate JSDoc at line ${i + 1}`);
      }
      pendingDescription = jsdoc[1];
      continue;
    }
    const match = ENTRY_RE.exec(line);
    if (!match) {
      throw new Error(`cannot parse line ${i + 1}: ${line}`);
    }
    entries.push({
      name: match[1]!,
      code: match[2]!,
      ...(pendingDescription !== undefined ? { description: pendingDescription } : {}),
    });
    pendingDescription = undefined;
  }
  throw new Error("enum was not closed");
}
